# Generated by Django 5.0.3 on 2024-02-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester', models.TextField()),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'messages',
            },
        ),
    ]
